#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Sep 13, 2021 12:31:56 PM -03  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1399x756+176+146
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Sketch - Analysis of Variance (ANOVA)"
    vTcl:DefineAlias "$top" "ToplevelAnova" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr45 \
        -borderwidth 1 -relief groove -width 1378 -height 186 
    vTcl:DefineAlias "$top.tFr45" "TFrameDataMainPage" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::label $top.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {bitstream charter} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {ANOVA Visual Analysis} 
    vTcl:DefineAlias "$top.tLa51" "TLabelInfoCompleteQuery" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::label $top.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {bitstream charter} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left \
        -text {ANOVA-based Query Results} 
    vTcl:DefineAlias "$top.tLa52" "TLabelInfoCorrelationQuery" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::separator $top.tSe53
    vTcl:DefineAlias "$top.tSe53" "TSeparator1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::separator $top.tSe54 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe54" "TSeparator2" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr55 \
        -borderwidth 1 -relief groove -width 699 -height 415 
    vTcl:DefineAlias "$top.tFr55" "TFrameDataMainPageCompQ" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr57 \
        -borderwidth 1 -relief groove -width 656 -height 405 
    vTcl:DefineAlias "$top.tFr57" "TFrameDataMainPageCorrQ" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa45 \
        -text {Run ANOVA over selected variables} -width 1251 -height 51 
    vTcl:DefineAlias "$top.tLa45" "TLabelframeQueryAttibutes" vTcl:WidgetProc "ToplevelAnova" 1
    set site_3_0 $top.tLa45
    ttk::combobox $site_3_0.tCo46 \
        -values Attributes -font TkTextFont -justify center \
        -textvariable comboAttReference1 -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo46" "TComboboxAttReference1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::combobox $site_3_0.tCo47 \
        -values Attributes -font TkTextFont -justify center \
        -textvariable comboAttReference2 -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo47" "TComboboxAttReference2" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::label $site_3_0.tLa48 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Categorical variable:} 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabelAtt1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::label $site_3_0.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Numerical variable:} 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabelAtt1_1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu50 \
        -command btnRunQueryANOVA -takefocus {} -text {Run ANOVA} 
    vTcl:DefineAlias "$site_3_0.tBu50" "btnRetrieveTuplesCorr_1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_3_0.tCh48 \
        -variable checkChartHorizontalVar -takefocus {} \
        -text {Horizontal Bars} 
    vTcl:DefineAlias "$site_3_0.tCh48" "TCheckbuttonChartHorizontal" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_3_0.tCh49 \
        -variable checkLabelChartVar -takefocus {} -text {Show Labels} 
    vTcl:DefineAlias "$site_3_0.tCh49" "TCheckbuttonChartShowLabel" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::separator $site_3_0.tSe50 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe50" "TSeparator3" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::separator $site_3_0.tSe53 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe53" "TSeparator3_1" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::label $site_3_0.tLa45 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -wraplength 80 -textvariable VarRunOutput 
    vTcl:DefineAlias "$site_3_0.tLa45" "TLabelRunOutput" vTcl:WidgetProc "ToplevelAnova" 1
    place $site_3_0.tCo46 \
        -in $site_3_0 -x 161 -y 15 -width 215 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 526 -y 15 -width 205 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 9 -y 20 -width 150 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 381 -y 20 -width 140 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 939 -y 13 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCh48 \
        -in $site_3_0 -x 744 -y 20 -width 89 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCh49 \
        -in $site_3_0 -x 835 -y 20 -width 99 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe50 \
        -in $site_3_0 -x 736 -y 13 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.tSe53 \
        -in $site_3_0 -x 933 -y 13 -width 1 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 1049 -y 12 -width 194 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu45 \
        -command btnCloseAnovaWindow -takefocus {} -text Close 
    vTcl:DefineAlias "$top.tBu45" "TButtonCloseAnovaWindow" vTcl:WidgetProc "ToplevelAnova" 1
    menu $top.m46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu51 \
        -command btnSaveBoxplotImage -takefocus {} -text {Save boxplot image} 
    vTcl:DefineAlias "$top.tBu51" "TButtonSaveBoxplotImage" vTcl:WidgetProc "ToplevelAnova" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu52 \
        -command btnSaveAnovaResults -takefocus {} -text {Save ANOVA results} 
    vTcl:DefineAlias "$top.tBu52" "TButtonSaveAnovaResults" vTcl:WidgetProc "ToplevelAnova" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr45 \
        -in $top -x 10 -y 66 -width 1378 -relwidth 0 -height 186 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 11 -y 261 -width 313 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 735 -y 262 -width 242 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe53 \
        -in $top -x 12 -y 262 -width 1377 -relwidth 0 -height 1 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe54 \
        -in $top -x 720 -y 269 -width 1 -relwidth 0 -height 482 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr55 \
        -in $top -x 10 -y 296 -width 699 -relwidth 0 -height 415 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 732 -y 297 -width 656 -relwidth 0 -height 415 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa45 \
        -in $top -x 10 -y 4 -width 1251 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 1270 -y 10 -width 115 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 10 -y 717 -width 699 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 732 -y 717 -width 656 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

