#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Sep 10, 2021 03:55:38 PM -03  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1501x919+124+101
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Sketch: Similarity Search and Tuple Correlation"
    vTcl:DefineAlias "$top" "ToplevelSimilarity" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr45 \
        -borderwidth 1 -relief groove -width 441 -height 386 
    vTcl:DefineAlias "$top.tFr45" "TFrameScatterMDSTraditional" vTcl:WidgetProc "ToplevelSimilarity" 1
    labelframe $top.lab45 \
        -font TkDefaultFont -foreground black \
        -text {Correlation Analysis (it may take a while)} \
        -background $vTcl(actual_gui_bg) -height 116 -highlightcolor black \
        -width 370 
    vTcl:DefineAlias "$top.lab45" "LabelframeCorrelationMenu" vTcl:WidgetProc "ToplevelSimilarity" 1
    set site_3_0 $top.lab45
    ttk::label $site_3_0.tLa46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {} -relief flat -anchor w -justify left \
        -text {Sample size (%):} 
    vTcl:DefineAlias "$site_3_0.tLa46" "TLabelCorrelationSamplePercent" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu47 \
        -command btnComputeCorrelation -takefocus {} \
        -text {Compute Correlation
and Plot Heatmap} 
    vTcl:DefineAlias "$site_3_0.tBu47" "btnComputeCorrelation" vTcl:WidgetProc "ToplevelSimilarity" 1
    spinbox $site_3_0.spi48 \
        -activebackground #f9f9f9 -background white \
        -font {-family gothic -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -justify right -selectbackground blue -selectforeground white \
        -textvariable SpinboxPercentSampleData -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi48" "SpinboxPercentSampleData" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::label $site_3_0.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {} -relief flat -anchor w -justify left \
        -textvariable RunningTextVar 
    vTcl:DefineAlias "$site_3_0.tLa51" "TLabelRunningText" vTcl:WidgetProc "ToplevelSimilarity" 1
    checkbutton $site_3_0.che45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Attribute Name} -variable varCheckHeatLegend 
    vTcl:DefineAlias "$site_3_0.che45" "CheckbuttonHeatLegend" vTcl:WidgetProc "ToplevelSimilarity" 1
    checkbutton $site_3_0.che46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text Colorbar -variable varCheckHeatBar 
    vTcl:DefineAlias "$site_3_0.che46" "CheckbuttonHeatBar" vTcl:WidgetProc "ToplevelSimilarity" 1
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 6 -y 30 -width 120 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 193 -y 20 -width 154 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi48 \
        -in $site_3_0 -x 134 -y 37 -width 48 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 20 -y 80 -width 162 -relwidth 0 -height 13 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che45 \
        -in $site_3_0 -x 200 -y 63 -width 118 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che46 \
        -in $site_3_0 -x 199 -y 90 -width 76 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr46 \
        -borderwidth 2 -relief groove -width 600 -height 725 
    vTcl:DefineAlias "$top.tFr46" "TFrameHeatmapFig" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa47 \
        -text {Similarity Query weighted by Correlation} -relief groove \
        -width 975 -height 115 
    vTcl:DefineAlias "$top.tLa47" "TLabelframe2" vTcl:WidgetProc "ToplevelSimilarity" 1
    set site_3_0 $top.tLa47
    ttk::label $site_3_0.tLa48 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Object query index} 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabelQIndex" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::label $site_3_0.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {k value (for kNN)} 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabelKValue" vTcl:WidgetProc "ToplevelSimilarity" 1
    spinbox $site_3_0.spi50 \
        -activebackground #f9f9f9 -background white \
        -font {-family gothic -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -justify right -selectbackground blue -selectforeground white \
        -textvariable spinboxQueryIndex -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi50" "SpinboxQueryIndex" vTcl:WidgetProc "ToplevelSimilarity" 1
    spinbox $site_3_0.spi51 \
        -activebackground #f9f9f9 -background white \
        -font {-family gothic -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -justify right -selectbackground blue -selectforeground white \
        -textvariable spinboxQueryKNN -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi51" "SpinboxQueryKValue" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu53 \
        -command btnRetrieveTuplesCorr -takefocus {} \
        -text {Run Correlated Query} 
    vTcl:DefineAlias "$site_3_0.tBu53" "btnRetrieveTuplesCorr" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::label $site_3_0.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Radius (for RangeQ)} 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabelKValue_1" vTcl:WidgetProc "ToplevelSimilarity" 1
    spinbox $site_3_0.spi55 \
        -activebackground #f9f9f9 -background white \
        -font {-family gothic -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground black -from 0.0 -highlightbackground black \
        -highlightcolor black -increment 0.1 -insertbackground black \
        -justify right -selectbackground blue -selectforeground white \
        -textvariable spinboxQueryRadius -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi55" "SpinboxQueryRadiusValue" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::combobox $site_3_0.tCo45 \
        -values Attributes \
        -font {-family gothic -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -justify center -textvariable comboboxAttRefQ -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo45" "TComboboxAttReferenceQ" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu49 \
        -command btnRetrieveTuples -takefocus {} \
        -text {Run Traditional Query} 
    vTcl:DefineAlias "$site_3_0.tBu49" "btnRetrieveTuples" vTcl:WidgetProc "ToplevelSimilarity" 1
    button $site_3_0.but51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command btnScatterPlot \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Show MDS in Scatter Plot} \
        -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but51" "btnScatterPlot" vTcl:WidgetProc "ToplevelSimilarity" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Reference Attribute} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1" vTcl:WidgetProc "ToplevelSimilarity" 1
    radiobutton $site_3_0.rad53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command cmbKnnSelected \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text kNN -value 1 \
        -variable radioQueryVar 
    vTcl:DefineAlias "$site_3_0.rad53" "RadiobuttonKNNOption" vTcl:WidgetProc "ToplevelSimilarity" 1
    radiobutton $site_3_0.rad54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command cmbRangeSelected \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Range -value 0 \
        -variable radioQueryVar 
    vTcl:DefineAlias "$site_3_0.rad54" "RadiobuttonRangeOption" vTcl:WidgetProc "ToplevelSimilarity" 1
    button $site_3_0.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command btnScatterPlotCorr \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black \
        -text {Show MDS in Scatter Plot with Correlations} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but46" "btnScatterPlotCorr" vTcl:WidgetProc "ToplevelSimilarity" 1
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 142 -y 30 -width 140 -relwidth 0 -height 13 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 144 -y 60 -width 121 -relwidth 0 -height 13 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi50 \
        -in $site_3_0 -x 295 -y 27 -width 51 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi51 \
        -in $site_3_0 -x 295 -y 56 -width 51 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 590 -y 65 -width 244 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 143 -y 90 -width 140 -relwidth 0 -height 13 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi55 \
        -in $site_3_0 -x 295 -y 86 -width 51 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo45 \
        -in $site_3_0 -x 590 -y 30 -width 244 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 380 -y 65 -width 184 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 10 -y 22 -width 110 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 590 -y 10 -width 149 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 392 -y 30 -width 45 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad54 \
        -in $site_3_0 -x 461 -y 30 -width 99 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 850 -y 21 -width 110 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::label $top.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {bitstream charter} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left \
        -text {Traditional Query Results} 
    vTcl:DefineAlias "$top.tLa51" "TLabelInfoCompleteQuery" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::label $top.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {bitstream charter} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left \
        -text {Correlation-based Query Results} 
    vTcl:DefineAlias "$top.tLa52" "TLabelInfoCorrelationQuery" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr55 \
        -borderwidth 1 -relief groove -width 849 -height 156 
    vTcl:DefineAlias "$top.tFr55" "TFrameDataMainPageCompQ" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr57 \
        -borderwidth 1 -relief groove -width 849 -height 166 
    vTcl:DefineAlias "$top.tFr57" "TFrameDataMainPageCorrQ" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr56 \
        -borderwidth 1 -relief groove -width 401 -height 386 
    vTcl:DefineAlias "$top.tFr56" "TFrameScatterMDSCorrelation" vTcl:WidgetProc "ToplevelSimilarity" 1
    menu $top.m45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu47 \
        -command TButtonCloseSimilarity -takefocus {} -text Close 
    vTcl:DefineAlias "$top.tBu47" "TButtonCloseSimilarity" vTcl:WidgetProc "ToplevelSimilarity" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu48 \
        -command btnSaveHeatmap -takefocus {} -text {Save heatmap image} 
    vTcl:DefineAlias "$top.tBu48" "TButtonSaveHeatmap" vTcl:WidgetProc "ToplevelSimilarity" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr45 \
        -in $top -x 632 -y 130 -width 441 -relwidth 0 -height 386 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 20 -y 10 -width 370 -relwidth 0 -height 116 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr46 \
        -in $top -x 20 -y 131 -width 600 -relwidth 0 -height 725 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 399 -y 10 -width 975 -relwidth 0 -height 115 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 640 -y 517 -width 223 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 640 -y 711 -width 313 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr55 \
        -in $top -x 633 -y 550 -width 849 -relwidth 0 -height 156 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 633 -y 739 -width 849 -relwidth 0 -height 166 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tFr56 \
        -in $top -x 1084 -y 130 -width 400 -relwidth 0 -height 386 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu47 \
        -in $top -x 1380 -y 20 -width 104 -relwidth 0 -height 102 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 18 -y 860 -width 604 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

